default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: mishalandsamuel
  port: 5432
  username: dev
  password: test
